Use environment in package scripts

diff --git a/package-pre b/package-pre
--- a/package-pre
+++ b/package-pre
@@ -5,14 +5,34 @@ NOTARY=$TOGETHER/notary
 PACKAGE=$TOGETHER/package
 MOUNT="/Volumes/Together"
 
-if [[ "$(arch)" == "arm64" ]]; then
-  APP="together-prod-silicon"
-  TEMPLATE_DMG="TogetherTemplateSilicon.dmg"
-  TOGETHER_DMG="Together Apple Silicon.dmg"
+if [ -f ".jaz" ]; then
+  . "$(pwd)/.jaz"
 else
-  APP="together-prod-mac"
+  echo ".jaz not found"
+  exit 1
+fi
+
+if [ -z "$JAZCONF" ]; then
+  echo "JAZCONF not set"
+  exit 1
+else
+  ENVIRONMENT="$JAZCONF"
+fi
+
+if [[ "$ENVIRONMENT" == "prod" ]]; then
+  SUFFIX=""
+else
+  SUFFIX=" Test"
+fi
+
+if [[ "$(arch)" == "arm64" ]]; then
+  APP="together-$ENVIRONMENT-silicon"
+  TEMPLATE_DMG="TogetherTemplateSilicon.dmg"
+  TOGETHER_DMG="Together$SUFFIX Apple Silicon.dmg"
+else
+  APP="together-$ENVIRONMENT-mac"
   TEMPLATE_DMG="TogetherTemplate.dmg"
-  TOGETHER_DMG="Together.dmg"
+  TOGETHER_DMG="Together$SUFFIX.dmg"
 fi
 
 # Bail out
@@ -37,4 +57,4 @@ fi
 hdiutil create -quiet -volname Together -fs HFS+ -size 400m -attach "$TEMPLATE_DMG"
 
 # Copy files
-# cp -R $NOTARY/$APP.app $MOUNT/Together.app
+# cp -R $NOTARY/$APP.app $MOUNT/Together$SUFFIX.app
